// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "huey_yu@acebiotek.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users": {
            "get": {
                "description": "取得使用者資料清單，不輸入過濾參數則回傳所有用戶資料。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "取得使用者資料清單",
                "parameters": [
                    {
                        "type": "string",
                        "description": "使用者帳號",
                        "name": "account",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "使用者電子郵件",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "使用者名稱",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "desc",
                            "asc"
                        ],
                        "type": "string",
                        "description": "排序，預設 ` + "`" + `desc` + "`" + `",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "account",
                            "name",
                            "userRoleName",
                            "email"
                        ],
                        "type": "string",
                        "description": "排序欄位",
                        "name": "orderBy",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "頁碼",
                        "name": "pageNumber",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每頁資料比數",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "使用者角色名稱",
                        "name": "userRoleName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.JSONResultDataList"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/models.UserResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "新增使用者",
                "parameters": [
                    {
                        "description": "新增使用者資料",
                        "name": "addUserData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parameters.AddUser"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "successful operation",
                        "schema": {
                            "$ref": "#/definitions/utils.JSONResultData"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "登入使用者帳號",
                "parameters": [
                    {
                        "description": "登入資料",
                        "name": "loginData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parameters.Login"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "successful operation",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.JSONResultData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/logout": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "登出使用者帳號",
                "responses": {
                    "204": {
                        "description": "no content data",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/personalProfile": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "取得使用者個人資料",
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.JSONResultData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "修改使用者個人資料",
                "parameters": [
                    {
                        "description": "修改使用者個人資料",
                        "name": "modifyPersonalProfile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parameters.ModifyPersonalProfile"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content data",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/personalProfile/password": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "修改使用者個人密碼",
                "parameters": [
                    {
                        "description": "修改使用者個人密碼資料",
                        "name": "modifyUserPassword",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parameters.ModifyUserPassword"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content data",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "取得使用者資料",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "使用者ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "successful operation",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.JSONResultData"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/models.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "修改使用者資料",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "使用者ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "修改使用者資料",
                        "name": "modifyUserData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parameters.ModifyUser"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content data",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "刪除使用者",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "使用者ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content data",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{id}/password": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "修改使用者密碼",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "使用者ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "修改使用者密碼資料",
                        "name": "modifyUserPassword",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parameters.ModifyUserPassword"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content data",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.UserResponse": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string",
                    "example": "admin"
                },
                "email": {
                    "type": "string",
                    "example": "admin@testmail.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "管理者"
                },
                "userRole": {
                    "$ref": "#/definitions/models.UserRole"
                }
            }
        },
        "models.UserRole": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 1
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "管理者"
                },
                "permission": {
                    "type": "string",
                    "example": "{}"
                }
            }
        },
        "parameters.AddUser": {
            "type": "object",
            "required": [
                "account",
                "email",
                "name",
                "password",
                "password2",
                "userRoleName"
            ],
            "properties": {
                "account": {
                    "type": "string",
                    "example": "normal_user"
                },
                "email": {
                    "type": "string",
                    "example": "normal_user@testmail.com"
                },
                "name": {
                    "type": "string",
                    "example": "普通的使用者"
                },
                "password": {
                    "type": "string",
                    "example": "normalguy123"
                },
                "password2": {
                    "type": "string",
                    "example": "normalguy123"
                },
                "userRoleName": {
                    "type": "string",
                    "enum": [
                        "管理者",
                        "一般使用者"
                    ]
                }
            }
        },
        "parameters.Login": {
            "type": "object",
            "required": [
                "account",
                "password"
            ],
            "properties": {
                "account": {
                    "type": "string",
                    "example": "admin"
                },
                "password": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "parameters.ModifyPersonalProfile": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "daming_wang@testmail.com"
                },
                "name": {
                    "type": "string",
                    "example": "王大明"
                }
            }
        },
        "parameters.ModifyUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "daming_wang@testmail.com"
                },
                "name": {
                    "type": "string",
                    "example": "王大明"
                },
                "userRoleName": {
                    "type": "string",
                    "enum": [
                        "管理者",
                        "一般使用者"
                    ]
                }
            }
        },
        "parameters.ModifyUserPassword": {
            "type": "object",
            "required": [
                "password",
                "password2"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "password2": {
                    "type": "string"
                }
            }
        },
        "utils.JSONResultData": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "error_code": {
                    "type": "integer",
                    "example": 20001
                },
                "error_message": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "utils.JSONResultDataList": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "error_code": {
                    "type": "integer",
                    "example": 20001
                },
                "error_message": {
                    "type": "string",
                    "example": "ok"
                },
                "pages": {
                    "type": "integer",
                    "example": 10
                }
            }
        }
    },
    "tags": [
        {
            "description": "使用者",
            "name": "users"
        }
    ]
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0.0",
	Host:        "localhost:3000",
	BasePath:    "/api",
	Schemes:     []string{"http", "https"},
	Title:       "Go Demo API Server",
	Description: "## 摘要\n可用來做為 GO API Server 教學展示或 API 服務基礎模板\n## Swagger API 認證\n以 **[POST] /users/login** API 取得token，點選文件頁面右側 Authorize 按鈕輸入token 作為Value儲存認證",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
